import { StyleSheet } from "react-native";

const HomeStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF5F5",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 16,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  logo: {
    width: 40,
    height: 40,
    marginRight: 12,
    borderRadius: 20,
  },
  appNameContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  appNameSnap: {
    fontSize: 24,
    fontWeight: "800",
    fontFamily: "Poppins",
    color: "#0f162b",
    letterSpacing: -0.6,
    lineHeight: 32,
  },
  appNameMap: {
    fontSize: 24,
    fontWeight: "800",
    fontFamily: "Poppins",
    color: "#f43f5e",
    letterSpacing: -0.6,
    lineHeight: 32,
  },
  notificationButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  notificationBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#EF4444",
  },
  discoverySection: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  discoveryTitle: {
    fontSize: 32,
    fontFamily: "Poppins",
    color: "#000000",
    marginBottom: 8,
    lineHeight: 35.2,
    letterSpacing: 0,
  },
  discoverText: {
    fontSize: 32,
    fontWeight: "800",
    fontFamily: "Poppins",
    color: "#000000",
    lineHeight: 35.2,
    letterSpacing: 0,
  },
  campusLifeText: {
    fontSize: 32,
    fontWeight: "800",
    fontFamily: "Poppins",
    color: "#f43f5e",
    textDecorationLine: "underline",
    textDecorationColor: "#FFB3C1",
    textDecorationStyle: "solid",
    lineHeight: 35.2,
    letterSpacing: 0,
  },
  discoverySubtitle: {
    fontSize: 16,
    color: "#6B7280",
    fontWeight: "400",
    fontFamily: "Inter",
  },
  mapCard: {
    marginHorizontal: 20,
    marginBottom: 0,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    height: 400,
  },
  map: {
    width: "100%",
    height: "100%",
  },
  liveIndicator: {
    position: "absolute",
    top: 16,
    left: 16,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#10B981",
    marginRight: 6,
  },
  liveText: {
    fontSize: 12,
    fontWeight: "600",
    fontFamily: "Inter",
    color: "#000000",
    marginRight: 6,
  },
  activeText: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "500",
    fontFamily: "Inter",
  },
  sendButton: {
    position: "absolute",
    top: 16,
    right: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  fullMapCard: {
    position: "absolute",
    bottom: 16,
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 12,
    zIndex: 10,
  },
  fullMapIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#F5385D",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  fullMapTextContainer: {
    flex: 1,
  },
  fullMapSubtext: {
    fontSize: 12,
    color: "#6B7280",
    fontFamily: "Inter",
    marginBottom: 2,
  },
  fullMapText: {
    fontSize: 16,
    fontWeight: "bold",
    fontFamily: "Inter",
    color: "#000000",
  },
});

export default HomeStyle;
